[profile.dev]
opt-level = 3

[package]
name = "zksnark"
version = "0.1.0"
authors = ["ross"]

[lib]
crate-type = ["cdylib"]

[dependencies]
# rand = {version = "0.5", branch = "master", wasm-bindgen = true}
# rand = { git = "https://github.com/rust-random/rand", wasm-bindgen = true }
itertools = "0.6.0"
bn = {path = "../bn"}
wasm-bindgen = "0.2"
# wbg-rand = "0.4"

[dependencies.rand]
git = "https://github.com/rust-random/rand"
rev = "cbee7c8"
features = ["wasm-bindgen"]