[profile.dev]
opt-level = 3

[package]
name = "zksnark"
description = "An implementation of zkSNARK using groth16"
version = "0.0.1"
authors = ["Ross"]
license = "gplv3"

[dependencies]
itertools = "0.6.0"
rand = "~0.3.14"
bn = "0.4.3"
bigint = "4.4.0"

[dev-dependencies]
quickcheck = "0.7.1"
